const actionTypes = {
  CREATE_USER_STARTED: 'CREATE_USER_STARTED',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILED: 'CREATE_USER_FAILED',

  SIGN_IN_USER_STARTED: 'SIGN_IN_USER_STARTED',
  SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
  SIGN_IN_USER_FAILED: 'SIGN_IN_USER_FAILED',

  UPDATE_USER_STARTED: 'UPDATE_USER_STARTED',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

  LOG_OUT_STARTED: 'LOG_OUT_STARTED',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  LOG_OUT_FAILED: 'LOG_OUT_FAILED',
};

export default actionTypes;
