const actionTypes = {
  CREATE_USER_STARTED: 'CREATE_USER_STARTED',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILED: 'CREATE_USER_FAILED',

  SIGN_IN_USER_STARTED: 'SIGN_IN_USER_STARTED',
  SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
  SIGN_IN_USER_FAILED: 'SIGN_IN_USER_FAILED',
};

export default actionTypes;
