const actionTypes = {
  CREATE_USER_STARTED: 'CREATE_USER_STARTED',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILED: 'CREATE_USER_FAILED',

  SIGN_IN_USER_STARTED: 'SIGN_IN_USER_STARTED',
  SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
  SIGN_IN_USER_FAILED: 'SIGN_IN_USER_FAILED',

  UPDATE_USER_STARTED: 'UPDATE_USER_STARTED',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

  LOG_OUT_STARTED: 'LOG_OUT_STARTED',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  LOG_OUT_FAILED: 'LOG_OUT_FAILED',

  ADD_CHAT_STARTED: 'ADD_CHAT_STARTED',
  ADD_CHAT_SUCCESS: 'ADD_CHAT_SUCCESS',
  ADD_CHAT_FAILED: 'ADD_CHAT_FAILED',

  GET_CHAT_STARTED: 'GET_CHAT_STARTED',
  GET_CHAT_SUCCESS: 'GET_CHAT_SUCCESS',
  GET_CHAT_FAILED: 'GET_CHAT_FAILED',

  CHANGE_MESSAGES_STARTED: 'CHANGE_MESSAGES_STARTED',
  CHANGE_MESSAGES_SUCCESS: 'CHANGE_MESSAGES_SUCCESS',
  CHANGE_MESSAGES_FAILED: 'CHANGE_MESSAGES_FAILED',

  SEND_MESSAGES_STARTED: 'SEND_MESSAGES_STARTED',
  SEND_MESSAGES_SUCCESS: 'SEND_MESSAGES_SUCCESS',
  SEND_MESSAGES_FAILED: 'SEND_MESSAGES_FAILED',

};

export default actionTypes;
