import Head from 'next/head';
import Image from 'next/image';
import { io } from 'socket.io-client';
import { ChatList, Messages } from '../container';

export default function Home() {
  const socket = io('https://appId.api-region.cometchat.io/v3/roles');
  return (
    <div className="flex flex-row p-1 max-h-screen overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChatList />
      <Messages />
    </div>
  );
}
