import Head from 'next/head';
import Image from 'next/image';
import { ChatList, Messages } from '../container';

export default function Home() {
  return (
    <div className="flex flex-row p-1 max-h-screen overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChatList />
      <Messages />
    </div>
  );
}
