import Head from 'next/head';
import { useEffect, useState } from 'react';
import Cookies from 'universal-cookie';
import { useRouter } from 'next/router';
import { useDispatch, useSelector } from 'react-redux';
import { ChatList, Messages } from '../container';
import firebaseAdmin from '../firebaseAdmin';
import { AddChat } from '../components';
import { GET_CHAT_ACTION } from '../actions';

export default function Home() {
  const dispatch = useDispatch();
  const { auth } = useSelector((state) => state);
  const [openAddChat, setOpenAddChat] = useState(false);
  const router = useRouter();

  useEffect(() => {
    if (auth.response && auth.response.uid !== '') {
      dispatch(GET_CHAT_ACTION());
    } else {
      router.push('/signUp');
    }
  }, [auth]);
  return (
    <div className="home flex flex-row w-full max-w-full p-1 max-h-screen overflow-hidden">
      <Head>
        <title>mbkChat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddChat openAddChat={openAddChat} setOpenAddChat={setOpenAddChat} />
      <ChatList setOpenAddChat={setOpenAddChat} />
      <Messages />

    </div>
  );
}

export const getServerSideProps = async ({ req }) => {
  // console.log('req :>> ', req.);
  const cookies = new Cookies(req.headers.cookie);
  const cookieToken = cookies.get('token');
  try {
    await firebaseAdmin.auth().verifyIdToken(cookieToken);
    return {
      props: {},
    };
  } catch (e) {
    cookies.set('token', '', { path: '/' });
    return {
      redirect: { destination: '/signUp' },
    };
  }
};
// export const getServerSideProps = async ({ req }) => {
//   // console.log('req :>> ', req.);
//   const cookies = new Cookies(req.headers.cookie);
//   const cookieToken = cookies.get('token');
//   try {
//     await firebaseAdmin.auth().verifyIdToken(cookieToken);
//     return {
//       props: {},
//     };
//   } catch {
//     return {
//       redirect: { destination: '/signUp' },
//     };
//   }
// };
